// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwrtzjccpccmrlgcuzjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3cnR6amNjcGNjbXJsZ2N1emp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTQ0NzcsImV4cCI6MjA3MDc5MDQ3N30.dWwGr-5fP-pMerDRr-cvb42q5ZPBPYhi5_890bNJyws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});